# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --build-cache --daemon --configure-on-demand --parallel
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Move jars
      run: |
        mv bin/master-1.0-SNAPSHOT.jar ~/static/master/plugins
        mv bin/lobby-1.0-SNAPSHOT.jar ~/static/lobby000a/plugins
        mv bin/bungeecord-1.0-SNAPSHOT.jar ~/static/bungee000a/plugins
