# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --build-cache --daemon --configure-on-demand --parallel
    - name: Delete common jars
      run: |
        rm -rf bin/common-1.0-SNAPSHOT.jar
        rm -rf bin/core-1.0-SNAPSHOT.jar
        rm -rf bin/void-1.0-SNAPSHOT.jar
    - name: Upload built jars
      uses: actions/upload-artifact@v2
      with:
        name: jars
        path: bin/*.jar
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Download built jars
      uses: actions/download-artifact@v2
      with:
        name: jars
    - name: Create directory
      run: |
        mkdir -p ~/static/lobby000a/plugins/
        mkdir -p ~/static/bungee000a/plugins/
    - name: Move jars
      run: |
        mv bin/master-1.0-SNAPSHOT.jar ~/static/master/
        mv bin/lobby-1.0-SNAPSHOT.jar ~/static/lobby000a/plugins/
        mv bin/bungeecord-1.0-SNAPSHOT.jar ~/static/bungee000a/plugins/
    - name: Restart servers
      run: |
        tmux send-keys -t master C-c
        tmux send-keys -t lobby000a "stop" ENTER
        tmux send-keys -t bungee000a "end" ENTER

